Sequence diagrams
konopek1/sledz pull request #6
Opened 2021-04-21 09:04 UTC by kondera

4 sequence diagrams:
- product history
- searching for product
- observing and not observing product

2021-04-21 21:18 UTC, daronek6 requested changes
Jak ktoś usuwa produkt ze swojej listy obserwowanych to na serwerze nie przestaje ten produkt być śledzony.

2021-04-22 09:16 UTC, kondera commented
Aj, nie opisałem tego za dobrze. Chodzi mi o rekord, który pokazuje, że użytkownik X obserwuje produkt Y. Historia produktu Y nadal jest.

2021-04-23 07:30 UTC, daronek6 approved these changes, later dismissed

2021-04-23 07:54 UTC, Ugibugi approved these changes
Piekne XDD

2021-04-23 16:04 UTC, merged